grantmcdermott/tinyplot

DESCRIPTION
NEWS.md
R/by_aesthetics.R
R/plot2.R
inst/tinytest/_tinysnapshot/aesthetics_type_b.svg
inst/tinytest/_tinysnapshot/aesthetics_type_b_col_pch.svg
inst/tinytest/_tinysnapshot/aesthetics_type_b_lty.svg
inst/tinytest/helpers.R
inst/tinytest/test-aesthetics.R
inst/tinytest/test_plot2.R
man/plot2.Rd

This PR includes a minimal `tinysnapshot` setup and a few tests. You can change the `exit_file` call at the top of the file if you intend to re-generate snapshots on `"Darwin"`.
This PR allows users to specify `lty`, `col`, and `pch` by group. One nice benefit is that we can use the `col` argument to do black and white figures. For example:
``` r
library(plot2)
plot2(Temp ~ Day | Month, type = "b",
data = subset(airquality, Month %in% 5:7),
pch = 1:3, col = "black", lty = 1:3)
```

by_aesthetics.R + tinysnapshot

---

DESCRIPTION
inst/tinytest/helpers.R
inst/tinytest/test-README.R
inst/tinytest/test-misc.R
inst/tinytest/test-par_restore.R

No longer need it in `Remotes:`

tinytest 0.0.3 is now on CRAN

---

R/by_aesthetics.R
R/plot2.R
README.Rmd
README.md
inst/tinytest/test-README.R
inst/tinytest/test-aesthetics.R
man/plot2.Rd

Addresses the second part of #19 .
Some quick notes:
- I've left the default colour palette as Okabe-Ito for the moment to becnhmark against our existing test suite.
- I had to do some tricksy `substitute` footwork to get all eventualities covered, i.e. users can pass strings or functions, where we can still splice in the number of colours (groups) later on. Similarly, I also had to drop `palette` as an argument for `plot2.formula` and `plot2.density` and rather pass this through `...`. Otherwise `substitute` doesn’t work properly. Maybe there's a more failsafe way to do this?
Examples:
``` r
library(plot2)
plot2(
Temp ~ Day | Month, airquality,
type = "b", pch = 16
)
```
``` r
plot2(
Temp ~ Day | Month, airquality,
type = "b", pch = 16,
palette = "tableau 10"
)
```
``` r
plot2(
Temp ~ …
```

Unified palette arg

---

R/plot2.R

Avoids the following message for pointrange plots:
```r
Warning message:
In plot.xy(xy.coords(x, y), type = type, ...) :
plot type 'pointrange' will be truncated to first character
```

Hard code "p" type

---

DESCRIPTION
NEWS.md
R/by_aesthetics.R
R/plot2.R
man/plot2-package.Rd
man/plot2.Rd

Closes #48. Closes #49.
In addition to specifying these parameters manually, this PR also permits `bg = "by"` (similar to existing "by" keyword support for `lty` and `pch`).
I haven't added `cex = "by"` keword support yet, because I need to solve the potential problem of dual legend placement, e.g. one legend for colors and another for cex/size. However, once that's been cracked then it should be fairly trivial to support "bubble" plot types (c.f., #29).
Quick example of what this PR allows:
``` r
library(plot2)
palette("Tableau 10")
palette(adjustcolor(palette() , 0.3))
plot2(
Sepal.Length ~ Petal.Length | Species, iris,
pch = 21,
col = "black",
bg = "by",
cex = 2
)
```
<sup>Created on 2023-07-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Support cex and bg

---

DESCRIPTION
NEWS.md
R/plot2.R
inst/tinytest/_tinysnapshot/ylab_good.svg
inst/tinytest/test-README.R
inst/tinytest/test-label.R
inst/tinytest/test-par_restore.R
inst/tinytest/test-type-other.R

Same as #51, close #47
Much better like this @grantmcdermott

 Fix y-title for function names 

---

DESCRIPTION
NEWS.md
R/plot2.R
inst/tinytest/_tinysnapshot/ribbon.svg
inst/tinytest/_tinysnapshot/ribbon_no_y.svg
inst/tinytest/test-ribbon.R

Fixes #53 .
``` r
devtools::load_all("~/Documents/Projects/plot2")
#> ℹ Loading plot2
mod = lm(mpg ~ wt, mtcars)
pred = predict(mod, interval = "confidence")
mtcars2 = cbind(mtcars, pred)
with(
mtcars2,
plot2(
x = wt, y = fit,
ymin = lwr, ymax = upr,
type = "ribbon"
)
)
```
This PR also allows interval plot types (ribbon, pointrange, etc) to be specified without a yvar.
``` r
with(
mtcars2,
plot2(
x = wt, 
ymin = lwr, ymax = upr,
type = "ribbon"
)
)
```

Automatic ribbon order

---

DESCRIPTION
NEWS.md
R/plot2.R
inst/tinytest/_tinysnapshot/addTRUE.svg
inst/tinytest/test-misc.R
man/plot2.Rd

Closes #55. Simplifies things by ignoring the legend for any added elements. (Maybe we can revisit down the line.)
Simple penguins example.
``` r
library(plot2)
par(pch = 15)
data(penguins, package = "palmerpenguins")
plot2(bill_depth_mm ~ bill_length_mm | species, penguins, pch = "by", grid = TRUE)
penguins$pred = predict(lm(bill_depth_mm ~ bill_length_mm * species, penguins), newdata = penguins)
plot2(pred ~ bill_length_mm | species, penguins, type = "l", add = TRUE)
```
<sup>Created on 2023-08-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Support add=TRUE

---

DESCRIPTION
NEWS.md
R/plot2.R

quick examples:
``` r
devtools::load_all("~/Documents/Projects/plot2")
#> ℹ Loading plot2
par(pch = 16)
plot2(~ Temp, airquality)
```
``` r
plot2(~ Temp | Month, airquality, type = "b", par_restore = TRUE)
```
``` r
plot2(~ Temp | Day * Month, airquality, legend = FALSE)
```
<sup>Created on 2023-08-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Basic one-sided formula support

---

.github/workflows/R-CMD-check.yaml

My university has been slow to confirm my academic affiliation / courtesy appointment, so I'm about to run out of my current GitHub Education Discount :-/
Hopefully this is resolved soon, but I want to preemptively reduce the GHA load _just in case_.
Also, we only run the tests on Ubuntu, so the other runs are really just wasting energy up in the cloud.

Simplify GHA runners

---

DESCRIPTION
NEWS.md
R/plot2.R
man/plot2.Rd

Closes #61.
Supports `type = "density"` for both the atomic...
``` r
devtools::load_all("~/Documents/Projects/plot2")
#> ℹ Loading plot2
with(airquality, plot2(Temp, type = "density"))
```
``` r
with(airquality, plot2(Temp, type = "density", by = Month, bg = "by"))
```
... and one-sided formula methods:
``` r
plot2(~Temp, airquality, type = "density")
```
``` r
plot2(~Temp | Month, airquality, type = "density", bg = "by")
```

Support type = "density"

---

DESCRIPTION
NEWS.md
R/plot2.R
man/plot2.Rd

Closes #67.
(I also fixed a bug related to bespoke legends when passing to plot2.density via the one-sided formula method... but that's supplemental to the main purpose of the PR.)
Some quick examples.
``` r
devtools::load_all("~/Documents/Projects/plot2")
#> ℹ Loading plot2
plot2(sin(seq(0,10, .1)), type = "area")
```
``` r
plot2(mpg ~ wt, mtcars, type = "area")
```
And then some fancier examples because we can (TM).
``` r
par(las = 1)
plot2(
~Temp, airquality,
type = "area",
col = "darkcyan",
grid = TRUE, frame = FALSE
)
```
``` r
plot2(
~ Temp | Month, airquality,
type = "area",
grid = TRUE, frame = FALSE
)
```

Support area plot types

---

R/plot2.R

If `grid = TRUE` is specified, then the new `abline(... = pretty(extendrange(...)), ...)` is used now instead of `grid()` - and not just for date/time classes (see https://github.com/grantmcdermott/plot2/issues/77).
Reason: Unlike `grid()`, the function `pretty()` is generic. Thus, it can adapt better to axes for variables of other classes.
Only exception: For axes in logs, we still resort to using `grid()` which is likely handled better there.
Potential downside: In all cases I tried, the `pretty(extendrange(...))` approach yielded the same grid positions as `grid()`. But there may be situations when differences occur. However, in the examples I tried, I wasn't able to produce such a situation.

Handling of grid = TRUE

---

vignettes/intro_tutorial.Rmd

Grant @grantmcdermott , just a mini-update in response to <https://fosstodon.org/@devSJR/111838661757048332>. Do you prefer if I send you such modifications as PRs or should I merge myself (or commit directly in main)?

update color reference from arXiv to The R Journal

---

NEWS.md
R/draw_legend.R
R/tinyplot.R
inst/tinytest/_tinysnapshot/type_n.svg
inst/tinytest/_tinysnapshot/type_n_by.svg
inst/tinytest/test-misc.R
man/tinyplot.Rd

Closes #156.
``` r
tinyplot::plt(Sepal.Length ~ Petal.Length, data = iris, type = "n")
```
<sup>Created on 2024-06-23 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Support empty plots (`type = "n"`)

---

NEWS.md
R/draw_legend.R
R/tinyplot.R
inst/tinytest/_tinysnapshot/rect_by_fill.svg
inst/tinytest/_tinysnapshot/rect_simple.svg
inst/tinytest/test-rect.R
man/tinyplot.Rd

Closes #160.
Should also open the door up to other derivative plot types (most obviously histograms), as well as segments (which use a similar `xmin`.`ymin`,`xmax`,`ymax` coordinate logic).
Example: 
``` r
```
``` r
i = 4*(0:10)
plt(
xmin = 100+i,
ymin = 300+i,
xmax = 150+i,
ymax = 380+i,
by = i,
type = "rect",
fill = 0.3
)
```
<sup>Created on 2024-07-06 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Support type = "rect"

---

NEWS.md
R/by_aesthetics.R
R/tinyplot.R
inst/tinytest/_tinysnapshot/rect_by_fill.svg
inst/tinytest/_tinysnapshot/segments_by.svg
inst/tinytest/_tinysnapshot/segments_by_extra.svg
inst/tinytest/_tinysnapshot/segments_by_xequal.svg
inst/tinytest/_tinysnapshot/segments_by_yequal.svg
inst/tinytest/test-segments.R
man/tinyplot.Rd

Closes #162.
Examples:
``` r
```
``` r
set.seed(42L)
x = stats::runif(12); y <- stats::rnorm(12)
i = order(x, y); x <- x[i]; y <- y[i]
s = seq(length(x)-1)  # one shorter than data
s = s[-length(s)]
grp = rep(LETTERS[1:2], 5)
plt(
xmin = x[s], ymin = y[s], xmax = x[s+2], ymax = y[s+2],
by = grp,
type = "segments"
)
```
``` r
plt(
xmin = x[s], ymin = y[s], xmax = x[s+2], ymax = y[s+2],
by = grp,
lty = "by", lwd = "by",
type = "segments"
)
```
``` r
plt(
xmin = x[s], ymin = y[s], xmax = x[s], ymax = y[s+2],
by = grp,
lty = "by", lwd = "by",
type = "segments"
)
```
``` r
plt(
xmin = x[s], ymin = y[s], xmax = x[s+2], ymax = y[s],
by = grp,
lty = "by", lwd = "by",
type = "segments"
)
```
<sup>Created on 2024-07-07 with …

Support type = "segments"

---

R/tinyplot.R

Hi @grantmcdermott, I've made a new package to find lints and automatically fix them ([`flint`](https://flint.etiennebacher.com/)). I used `tinyplot` as one of my test cases and found a few lints so I thought you might want to remove them.
FYI those fixes were automatically generated with `flint::fix(exclude_linters = "equal_assignment")`. End of the self-advertising :)

Fix some lints

---

NEWS.md
R/tinyplot.R
inst/tinytest/_tinysnapshot/type_l_empty.svg
inst/tinytest/test-misc.R
man/tinyplot.Rd

Closes #166.
Allows users to produce empty plots, but still honour the type of legend that would have been produced by non-point type plots.
``` r
tinyplot::plt(Sepal.Length ~ Petal.Length | Species, data = iris, type = "l", empty = TRUE)
```
``` r
tinyplot::plt(~Petal.Length | Species, data = iris, type = "density", fill = "by", empty = TRUE)
```
<sup>Created on 2024-07-15 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Add `empty = <logical>` argument

---

DESCRIPTION
R/setup_device.R
R/tinyplot.R
inst/tinytest/test-misc.R

The `tinyplot()` function is currently over 1100 lines long, and I think it would be nice to add new features.
Would you be open to a few small PRs like this one, to split up the function in smaller, more manageable blocks?

refactor: setup_device()

---

R/sanitize.R
R/tinyplot.R
inst/tinytest/helpers.R
man/tinyplot.Rd

Closes #178.
``` r
pkgload::load_all("~/Documents/Projects/tinyplot")
```
``` r
plt(Sepal.Length ~ Species, iris, type = "jitter")
```
<sup>Created on 2024-07-30 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
(Beyond this specific example, setting  `type = NULL` rather than `type = "p"` simultaneously allows for more sensible default type override/assignment down the road).

type = NULL

---

DESCRIPTION
NEWS.md
R/tinyplot.R

Closes #186.
Culprit was duplicate `do.call(...)` lines here: https://github.com/grantmcdermott/tinyplot/blob/f5436fcc9c1b6d206b4cd9b2aee1de169031b232/R/tinyplot.R#L603-L604
``` r
pkgload::load_all("~/Documents/Projects/tinyplot")
plt(
~ Petal.Length | Species,
data = iris,
type = "density",
palette = "dark", fill = "by",
grid = TRUE,
main = "Distribution of petal lengths by species"
)
```
<sup>Created on 2024-08-02 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Fix duplicate density call

---

R/tinyAxis.R
R/tinyplot.R
man/tinyplot.Rd

As discussed in https://github.com/grantmcdermott/tinyplot/issues/182 I have tried to implement character specifications of different axis types. The docs of the relevant arguments in `tinyplot.default` now say:
* `axes`: logical or character. Should axes be drawn (`TRUE` or `FALSE`)? Or alternatively what type of axes should be drawn: `"standard"` (with axis, ticks, and labels; equivalent to `TRUE`), `"none"` (no axes; equivalent to `FALSE`), `"ticks"` (only ticks and labels without axis line), `"labels"` (only labels without ticks and axis line), `"axis"` (only axis line and labels but no ticks). To control this separately for the two axes, use the character specifications for `xaxt` and/or `yaxt`.
* `xaxt`, `yaxt`: character specifying the type of x-axis and y-axis, respectively. See …

Fine control of axis types in axes/xaxt/yaxt

---

NEWS.md
R/draw_elements.R
R/tinyplot.R
inst/tinytest/_tinysnapshot/boxplot_facet_by_x_same.svg
inst/tinytest/_tinysnapshot/boxplot_groups_x_equivalent.svg
inst/tinytest/_tinysnapshot/boxplot_groups_x_equivalent_legendFALSE.svg
inst/tinytest/_tinysnapshot/boxplot_groups_x_same.svg
inst/tinytest/_tinysnapshot/boxplot_groups_x_same_legendFALSE.svg
inst/tinytest/test-boxplot.R
man/tinyplot.Rd

Boxplot widths

---

R/tinyplot.R
man/tinyplot.Rd

This lonely backtick in the R file generated several `\verb{}` tags in the Rd file (cf https://github.com/etiennebacher/altdoc/issues/289#issuecomment-2285515243), which then messed up the formatting of the arguments section:
https://grantmcdermott.com/tinyplot/man/tinyplot.html#arguments
Fixing this typo also fixes the formatting on the website.
Related to https://github.com/etiennebacher/altdoc/issues/289

Fix typo in docs that affected the formatting on the website

---

R/facet.R
R/tinyformula.R
R/tinyplot.R

Fixes https://github.com/grantmcdermott/tinyplot/issues/191
I started to work on a completely revised formula handling to address the issue above. This is still leaner than employing the `Formula` package but uses a similar approach:
- Auxiliary function `tinyformula` explicitly breaks up the formulas into separate formulas for `x`, `y` (if any), `by` (if any), and `facet` (if a formula) plus a `full` formula combining all elements (on the right-hand side).
- Auxiliary function `tinyframe` to extract the variables from the different formulas from the overall model frame.
- This allows for better sanity checking, e.g., that there is exactly one `x` and at most one `y` etc.
By and large things seem to work. However, I have apparently messed up the two-sided `facet` formulas. Grant …

Formula processing

---

R/tinyplot.R

Fixes #217
**Summary:** In `tinyplot.default` the `x`, `y`, and `by` variables are turned into factors if they are character variables. This is done early on in the function but after all `deparse1(substitute(...))` calls because the coercion would evaluate the variables obviously.
**Caveat:** In the modular future we might have tinyplot types which want to draw character variables in some way. As long as the type "knows" that, it's not yet a killer argument. The plot type could coerce back with `as.character()` and end up with the original variable. However, if that plot type would do somewhat different things for character variables and factor variables, then the design decision from this PR would prevent that.

Coerce x/y/by from character to factor

---

NEWS.md
R/facet.R
R/tpar.R
R/zzz.R
inst/tinytest/_tinysnapshot/tpar_grid.svg
inst/tinytest/test-tpar.R
man/tpar.Rd

Closes #235.
``` r
pkgload::load_all(("~/Documents/Projects/tinyplot"))
op = tpar(grid.col = "hotpink", grid.lty = "solid", grid.lwd = 2)
plt(0:10, pch = 19, grid = TRUE)
```
``` r
tpar(op) # reset defaults
plt(0:10, pch = 19, grid = TRUE)
```
<sup>Created on 2024-10-29 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Support `grid()` args in tpar

---

NEWS.md
R/tinyplot.R
R/type_ribbon.R
inst/tinytest/_tinysnapshot/ribbon_alpha50.svg
inst/tinytest/test-ribbon.R
man/tinyplot.Rd
man/type_ribbon.Rd

Test now looks like this:
```r
f = function() {
with(
mtcars2,
tinyplot(
x = wt, y = fit,
ymin = lwr, ymax = upr,
type = type_ribbon(alpha = .5)
)
)
}
expect_snapshot_plot(f, label = "ribbon_alpha50")
```

Issue #225 Deprecate ribbon.alpha

---

R/tinyplot_add.R
inst/tinytest/_tinysnapshot/tinyplot_add_unnamed.svg
inst/tinytest/helpers.R
inst/tinytest/test-tinyplot_add.R

This allows `tinyplot_add` to have a first unnamed argument. It's convenient when we want to overwrite the formula of a function. Ex: `mpg~hp|cyl` in one plot and `mpg~hp` in a layer on top.
Very small change with low impact and risk. If the tests pass, I'll probably just merge right away.

tinyplot_add first argument can be unnamed

---

R/type_text.R
man/type_text.Rd

Should be unobjectionable. i'll merge if the tests pass.

Fixing minor error in the `type_text()`

---

vignettes/introduction.qmd

The `plt()` tooltip is great and highly visible.
I moved it to just after we call `tinyplot()` for the first time, so users see it immediately.
I removed the section on `plt()`. IMHO, the tooltip is already very visible, and spending a full section on an alias at the top of the intro vignette is overkill. The start of the introduction in prime real estate in a tutorial, and we should invest it on "real" features.

intro plt() alias discussion

---

R/tinyplot.R
R/type_histogram.R
man/type_histogram.Rd

Closes #293 
(I'm not including `probability` since its duplication with `freq` and is a pain to support with arg passing through our sub function logic.)

Support additional `type_hist()` args

---

R/type_ridge.R
man/type_ridge.Rd

Grant @grantmcdermott, this is a follow-up to our discussion in #270 
I replaced the old `global.max = TRUE` vs. `FALSE` argument with a new `joint.max = "all"` vs. `"facet"` or `"by"`. The documentation reads as follows.
`joint.max`: character indicating how to scale the maximum of the densities: The default `"all"` indicates that all densities are scaled jointly relative to the same maximum so that the areas of all densities are comparable. Alternatively, `"facet"` indicates that the maximum is computed within each facet so that the areas of the densities are comparable within each facet but not necessarily across facets. Finally, `"by"` indicates that each row (in each facet) is scaled separately, so that the areas of the densities for `by` groups in the same row are comparable but not …

type_ridge: joint.max=all/facet/by instead of global.max=TRUE/FALSE

---

NEWS.md
R/draw_legend.R

Fixes #319. Looking at the issue I posted earlier, it appears that the jitter plot is internally referenced as "p" type. While my knowledge of this codebase is next to nothing, I don't believe there should be unintended consequences of this change because "p" should only include points. The changes allow for the legend to pick up the `lwd` argument in the case that the `pch` used during plotting can be impacted by that value. Happy to hear more if I have misunderstood this :)
``` r
set.seed(0)
x <- rep(c("A", "B", "C"), each = 20)
y <- runif(60)
gp <- sample(c("X", "Y", "Z"), size = 60, replace = TRUE)
df <- data.frame(x, y, gp)
library(tinyplot)
utils::packageVersion("tinyplot")
#> [1] '0.3.0.99'
plt(
y ~ x | gp,
data = df,
pch = 0:2,
lwd = 4,
type = type_jitter()
)
```

assign pt.lwd for type "p" in legend

---

NEWS.md
R/sanitize.R
R/type_jitter.R
R/type_points.R

Closes #321 
``` r
set.seed(0)
x <- rep(c("A", "B", "C"), each = 20)
y <- runif(60)
gp <- sample(c("X", "Y", "Z"), size = 60, replace = TRUE)
df <- data.frame(x, y, gp)
plt(
y ~ x | gp,
data = df
)
```
I also addressed/enabled factor variable support for `type_points()`.
``` r
plt(
y ~ x | gp, pch = 0:2,
data = df,
type = type_points()
)
```
Note: the basic `"p"` type isn't working (I think b/c of #322).
``` r
plt(
y ~ x | gp, pch = 0:2,
data = df,
type = "p"
)
#> Error in Summary.factor(structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, : 'range' not meaningful for factors
```
<sup>Created on 2025-02-17 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Characters variables inherit same default behaviour as factors

---

NEWS.md
R/by_aesthetics.R
R/tinyplot.R
inst/tinytest/_tinysnapshot/palette_manual.svg
inst/tinytest/_tinysnapshot/palette_manual_continuous.svg
inst/tinytest/test-palette.R
man/tinyplot.Rd
tinyplot.Rproj

Fixes #324 
``` r
library(tinyplot)
library(palmerpenguins)
tinytheme("clean2", palette.qualitative = c("darkorange", "purple", "cyan4"))
plt(
bill_depth_mm ~ bill_length_mm | species, penguins,
pch = "by",
alpha = 0.8
)
```
``` r
tinytheme("clean2")
plt(
bill_depth_mm ~ bill_length_mm | species, penguins,
pch = "by",
alpha = 0.8,
palette = c("darkorange", "purple", "cyan4")
)
```
Colors are recycled with a warning if too few are provided.
``` r
plt(
bill_depth_mm ~ bill_length_mm | species, penguins,
pch = "by",
alpha = 0.8,
palette = c("darkorange", "purple")
)
#> Warning in by_col(ngrps = ngrps, col = col, palette = palette, gradient = by_continuous, : 
#> Fewer colours (2) provided than than there are groups …
```

Manual palette colours

---

DESCRIPTION
R/by_aesthetics.R

Fixes #326
``` r
pkgload::load_all(("~/Documents/Projects/tinyplot"))
data("penguins", package = "palmerpenguins")
tinyplot(bill_depth_mm ~ bill_length_mm, data = penguins, col = 4)
```
``` r
tinyplot(bill_depth_mm ~ bill_length_mm | sex, data = penguins, col = 3:4)
```
<sup>Created on 2025-02-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

col accepts numeric index

---

NEWS.md
R/tinyplot.R
R/type_boxplot.R
R/type_spineplot.R

_Motivated by various discussions, e.g. https://github.com/grantmcdermott/tinyplot/pull/233#issuecomment-2408778373, https://github.com/grantmcdermott/tinyplot/issues/305#issuecomment-2646688729, and https://github.com/grantmcdermott/tinyplot/pull/314#issuecomment-2661779442._
This PR switches the nested loop that we use for drawing interior plot elements. Specifically, the proposed new nesting logic is:
1. Outer loop over facets
2. Inner loop over groups (i.e., `by` within each facet)
The old nesting logic inverted this relationship&mdash;groups first, then facets&mdash;but this was mostly just an artifact of historical inertia. (I only implemented facet support much later than group support, which was enabled from the get-go.) In addition, the whole datapoints + dedicated types …

Switch nested drawing loop: First facets, then by groups

---

NEWS.md
R/type_text.R

`type_text()` accepts non-character labels

---

NEWS.md
R/by_aesthetics.R

Fixes #337 
``` r
xx = rnorm(1e4)
plt(xx, pch = ".", alpha = 0.3)
```
``` r
plt(mpg ~ wt | factor(am), mtcars, pch = c("X", "O"))
```
<sup>Created on 2025-03-11 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Support `pch` character literals

---

R/tinyplot.R
man/tinyplot.Rd

Fixes #339
After the discussion in the issue, I tried to address this with two improvements:
1. Explicit pointer to `I()` in the warning message.
2. More details in the documentation of the formula argument.
Example for 1:
```
tinyplot(mpg/hp ~ wt, data = mtcars)
```
From the `?tinyplot` documentation for argument `formula`:
> a `formula` that optionally includes grouping variable(s) after a vertical bar, e.g. `y ~ x | z`. One-sided formulae are also permitted, e.g. `~ y | z`. Only a single `y` and `x` variable (if any) must be specified but multiple grouping variables can be included in different ways, e.g. `y ~ x | z1:z2` or `y ~ x | z1 + z2`. (These two representations are treated as equivalent; both are parsed as `interaction(z1, z2)` internally.) If arithmetic operators are used for …

Dealing with y1/y2 ~ x formulas

---

vignettes/custom.css
vignettes/types.qmd

Purely aesthetic website change from the existing bullet points (which feel a bit crowded to me).
Thoughts?  We can merge if other folks think that it makes for an improved reading experience.
Screenshot:

Types vignette: list tinyplot types in neater table format

---

R/type_barplot.R

Fixes #344 
Previously `xaxt = "l"` was hard-coded. Now the factory-fresh default `xaxt = "s"` gets mapped to `xaxt = "l"` but all other `xaxt` types are still processed. Implications:
- Users can never set `xaxt = "s"` because it always gets overruled. But this might be tolerable because `"s"` never looks great anyway and they can emulate it by adding `xaxt = "a"` for example.
- If themes set another default axis type such as `"t"` ticks will now be drawn. Currently, we don't have such themes, though.
In short, I think this is better than before but maybe still not ideal.

xaxt processing in type_barplot

---

NEWS.md
R/type_lines.R
R/type_ribbon.R

Fixes #355
The `bg`/`fill` argument was not passed on correctly to the `draw_lines()` function in `type_lines()`. Fixed and documented now.

Pass on bg argument in type_lines

---

R/tinylabel.R
R/type_barplot.R
man/tinylabel.Rd
man/type_barplot.Rd

As discussed in #361 all `tinylabel()` specifications can optionally be used with an `abs_` prefix as well which will internally apply `abs()` before using the actual `format_*()` function.
This is convenient for centered bar plots and illustrated now in the `HairEyeColor` example in `?type_barplot`.

Absolute numbers in tinylabel() via abs_ prefix

---

NEWS.md
R/facet.R
inst/tinytest/_tinysnapshot/tinytheme_dynamic_clean_facet.svg
inst/tinytest/_tinysnapshot/tinytheme_dynamic_dark_facet.svg
inst/tinytest/_tinysnapshot/tinytheme_dynamic_x_boxplot.svg
inst/tinytest/test-tinytheme.R

Fixes #368 
``` r
tinytheme('clean', las = 2)
plt(Temp ~ I(1e5 * Month), data = airquality)
```
``` r
plt(Temp ~ I(month.name[Month]), data = airquality)
```
<sup>Created on 2025-04-10 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Fix dynamic x-axis spacing

---

R/tinyplot.R
R/type_barplot.R
R/type_boxplot.R
R/type_ribbon.R
R/type_ridge.R
R/type_spineplot.R
R/type_violin.R
man/type_barplot.Rd

Fixes #370 
... and simultaneously simplifies some other types, since I realised we could re-use the same `null_by` and `null_facet` args in a few other places. Determining them once and then passing down from the main `tinyplot.default` function thus reduces code and computation.

Pass `null_by` and `null_facet` args to `type_data`

---

R/tinylabel.R
R/tinyplot.R
man/tinylabel.Rd
man/tinyplot.Rd

This PR would allow users to pass the equivalent symbol as a(n even shorter) shortcut to `xaxl`/`yaxl`.  For example, `"percent"` <=> `"%"`, `"dollar"` <=> `"$"`, etc.
``` r
pkgload::load_all("~/Documents/Projects/tinyplot")
tinytheme('ipsum')
dat = data.frame(
x = rnorm(100, 1e3, 50),
y = rnorm(100, 1e3, 10)
)
plt(y ~ x, dat, xaxl = "€", yaxl = "$")
```
``` r
plt(y ~ I(x/1e4), dat, xaxl = "%", yaxl = ",")
```
``` r
tinytheme()
```
<sup>Created on 2025-04-10 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
Thoughts?

`xaxl`/`yaxl` symbol shortcuts

---

NEWS.md
R/facet.R
inst/tinytest/_tinysnapshot/type_j_y.svg
inst/tinytest/test-misc.R

Fixes #386.
``` r
tinytheme("bw")
plt(
species ~ flipper_len, data = penguins,
type = "p"
)
```
``` r
plt(
species ~ flipper_len, data = penguins,
type = "j"
)
```
<sup>Created on 2025-05-07 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Fix factor-based y-tick labels for "p"-alike plots

---

NEWS.md
R/draw_legend.R
R/tinyplot.R
man/draw_legend.Rd

Fixes #388 
I won't share just how many dead-ends I ended going down to resolve this. But I think I've cracked it now.
_tl;dr_ For reasons that I don't fully understand, we can't wrap the whole `draw_legend()` function in `recordGraphics()` without messing up source calls (which is what #388 was ultimately about.) At the same time, simply wrapping the final `legend`/`gradient_legend` calls didn't work either for the Positron case (per #377). _However_, it turns out that the compromise solution is to wrap the fake legend construction (which we need for calculating the plot offset for outside legend placement), the offset calculation, and the final legend plotting call together... but only these steps.
I operationalised this by creating a new internal `recordGraphics(tinylegend(...), ...)` …

recordGraphics redux

---

vignettes/tips.qmd

This vignette takes more than 2 min to render on my Windows machine. Using `n = 50000` doesn't change the main usecase.

Smaller `n` in "tips and tricks"

---

NEWS.md
R/type_barplot.R
R/type_spineplot.R
inst/tinytest/_tinysnapshot/barplot_xlevels_issue430.svg
inst/tinytest/test-type_barplot.R
man/type_barplot.Rd
man/type_spineplot.Rd

Fixes #430 
- Numeric `xlevels` specifications in `type_barplot()` never worked correctly because the `x` rather than `datapoints$x` was used in one place. Fixed now.
- Improved the documentation of `xlevels` and added two simple examples.
- Added a warning in cases where `xlevels` contains entries that do not correspond to any level of `x`.

fix numeric xlevels specification in type_barplot

---

NEWS.md
R/tinyplot.R
R/tinyplot_add.R
man/tinyplot_add.Rd

Supersedes #437 
Fixes https://github.com/grantmcdermott/tinyplot/issues/313
Fixes https://github.com/posit-dev/positron/issues/7316
It turns out that this simpler fix has the same effect of resolving the resizing issues, without the pathologies of #437. Thank goodness I'd been down the well for #394, otherwise I don't know if I would have cracked this.

Wrap saved_par in `recordGraphics`

---

.github/workflows/altdoc.yaml
DESCRIPTION

Testing the setup suggested by @etiennebacher here: https://github.com/etiennebacher/altdoc/issues/322#issuecomment-2794929124
This is so we can use the dev version of altdoc, but avoid having to comment things out for CRAN submission.
(I'm not sure that it will work given our reliance on Dirk's r-ci script, but let's see what CI throws up.)

Move altdoc to config

---

.github/workflows/altdoc.yaml

R-universe build doesn't work with r-ci (probably for override reasons) and just reverts to r2u/CRAN. (Details [here](https://github.com/grantmcdermott/tinyplot/actions/runs/16306381497/job/46053266747#step:7:165).) So now we try with `remotes` again and explicit GH token...

Revert to remotes

---

NEWS.md
R/tinyplot.R

Fixes #453 
Like `boxplot(x)` it would be good if `tinyplot(x, type = "boxplot")` created a single boxplot without a grouping variable (and without corresponding labels on the x-axis).
I think that this is not easy to handle in `type_boxplot()` but requires a few simple workarounds in `tinyplot.default()` where the `is.null(y)` cases are handled. I've added:
```
} else if (type == "boxplot") {
y = x
x = rep.int("", length(y))
xlab = ""
xaxt = "a"
```
With this both the default and the formula interface work:
```
tinyplot(Nile, type = "boxplot")
tinyplot(~ Nile, type = "boxplot")
```
Grouping and faceting still works:
```
tinyplot(~ bill_len | species, data = penguins, type = "boxplot")
```
```
tinyplot(~ bill_len, facet = ~ species, data = penguins, type = "boxplot")
```

handle boxplot without y-variable in tinyplot.default

---

R/draw_legend.R
R/draw_legend_utils.R
R/tinyplot.R
R/utils.R
inst/tinytest/test-tinyplot_add.R

The purpose of this PR is to simplify the logic of `draw_legends()` somewhat. The main strategy is to have a cleaner separate of concerns, with a cleaner difference between functions that are called to compute coordinates/settings and functions that are called to create side-effects.
I want to do this in a few more ways and think it will open up big long term benefits, perhaps in the same vein as the `type_*()` refactor.

Refactor `draw_legend()`

---

DESCRIPTION
NEWS.md
R/facet.R
R/tinyplot.R
R/zzz.R
man/facet.Rd

Fixes #474
I tracked the issue down to the fact the draw_facet_window ([here](https://github.com/grantmcdermott/tinyplot/blob/c17bbd72b343a6d469e0aba5b82fd170bc12001e/R/tinyplot.R#L1207)) is actually being called twice and, during the second time, it's dropping the `tpar` hooks.
While I'm not 100% certain of the mechanics, I'm pretty confident that this is another `recordGraphics` / `replayGraphics` gotcha. (Side note: but I think this only appears to affect `"dynmar"` among all of the sundry `tpar` parameters, because the rest are handled by native hooks that kick in once plot.new() is called.)
At any rate, the simple solution that I use here is just to pass `dynmar` as an explicit argument in `recordGraphics(draw_facet_window, list(..., dynmar = get_par("dynmar"))` I thought about …

Pass dynmar as explicit argument

---

.Rbuildignore
.devcontainer/devcontainer.json
NEWS.md

Add devcontainer

---

NEWS.md
R/tinytheme.R

Closes #477
``` r
pkgload::load_all('~/Documents/Projects/tinyplot')
tinyplot(dist ~ speed, data = cars)
```
``` r
tinytheme("clean2", pch = 17, cex = 3)
tinyplot(dist ~ speed, data = cars)
```
``` r
tinytheme()
tinyplot(dist ~ speed, data = cars)
```
<sup>Created on 2025-09-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Add `cex` as explicit argument to tinytheme

---

NEWS.md
R/tinyplot.R
R/tinytheme.R
inst/tinytest/_tinysnapshot/tinytheme_ephemeral.svg
inst/tinytest/test-tinytheme.R
man/tinyplot.Rd
man/tinytheme.Rd
vignettes/themes.qmd

Closes #442
MWE
``` r
pkgload::load_all('~/Documents/Projects/tinyplot')
plt(bill_dep ~ bill_len | species, data = penguins)
```
``` r
plt(bill_dep ~ bill_len | species, data = penguins, theme = 'clean')
plt_add(type = 'lm')
```
``` r
plt(bill_dep ~ bill_len | species, data = penguins)
```
<sup>Created on 2025-09-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Ephemeral `theme` arg

---

R/tinyplot.R
inst/tinytest/_tinysnapshot/tinyplot_add_no_recursive_margins.svg
inst/tinytest/test-tinyplot_add.R

Correct `set/get_saved_par` order

---

DESCRIPTION

v0.6.0 is on CRAN, so no need to install the dev version anymore

Bump altdoc verison

---

.Rbuildignore
CRAN-SUBMISSION
DESCRIPTION
NEWS.md
cran-comments.md

CRAN v0.5.0

---

DESCRIPTION
NEWS.md
R/type_points.R
R/type_text.R
inst/tinytest/_tinysnapshot/bubble_dual_continuous.svg
inst/tinytest/_tinysnapshot/bubble_dual_discrete.svg
inst/tinytest/_tinysnapshot/bubble_dual_fancy.svg
inst/tinytest/_tinysnapshot/bubble_simple.svg
inst/tinytest/_tinysnapshot/bubble_simple_bottom.svg
inst/tinytest/_tinysnapshot/bubble_simple_clim.svg

Fixes #497
```r
devtools::load_all()
library("gapminder")
with(
subset(gapminder, year == 2007),
plt(
x = gdpPercap, y = lifeExp,
by = continent, facet = continent,
pch = 21, bg = 0.4,
cex = pop, clim = c(0.5, 3.5),
main = "Gapminder!",
theme = "clean"
)
)
```

Bubble legend: drop smallest category if zero

---

NEWS.md
R/type_text.R
man/type_text.Rd

Fixes #501
Fixes #494
MWEs
``` r
plt(1:12, type = type_text())
```
``` r
plt(1:12, type = type_text(labels = month.abb, family = "HersheyScript"))
```
<sup>Created on 2025-09-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

`type_text()` improvements

---

NEWS.md
vignettes/tips.qmd

Tips & tricks vignette: recession bars
